name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Test
      run: |
        bundle exec ruby -Itest test/00_setup/test_try_out.rb
        bundle exec ruby -Itest test/02_object_model/test_hierarchy.rb
        bundle exec ruby -Itest test/02_object_model/test_object_model.rb
        bundle exec ruby -Itest test/03_method/test_define.rb
        # bundle exec rake
